### ISSUE TITLE
Feature: User can Create a Profile

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a profile 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By Answering questions the user will be able to provide information that will be displayed on their profile. The screen will be
prompted topic/question individually as the user can choose to skip or answer, name and picture will be required as the user clicks continue.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="188" alt="Screen Shot 2022-04-12 at 4 27 19 PM" src="https://user-images.githubusercontent.com/90487207/163070626-34d8c001-3b2b-43bb-94cf-ce696f0426f9.png">
<img width="489" alt="Screen Shot 2022-04-12 at 4 27 15 PM" src="https://user-images.githubusercontent.com/90487207/163070679-68c13985-2b5f-4a3d-bca4-c1f4876e773e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to  insert values for the specific userId  based on user inputs
- [x] This will update profiles table and their fields

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Create middleware for errors
- [x] create routes for post / get so that the user can insert values to the data 
- [x] make sure to create a db pool to build server
- [x] create a server folder with a public folder
- [x] create different js-files for uploads-middleware, errormiddle ware, and client error
- [x] dont forget to create dotenv and an index.js
- [x] download all the necessary dependencies/devdependencies
- [x] Create a fileupload middleware
- [x] build a webpack.config.js
- [x] npm init -y for package.json

### ⚡ Client

- [x] Create a component to root to the HTML
- [x] create a component for the continue button
- [x] create a component for  input values 
- [x] Make sure to hash route the pages 
- [x] Make sure that input values are correctly being store and sent
- [x] Make sure you are using media queries for responsive design
- [x] Update component to  switch topics and form controls depending on the question

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
