### ISSUE TITLE
Feature 2: User can Select a Location

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can select a geolocation

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After being asked for permission to enable location services, the user can type a location or drop a pin on the map indicating their location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="489" alt="Screen Shot 2022-04-12 at 4 27 15 PM" src="https://user-images.githubusercontent.com/90487207/163072794-f8ca1ac1-c428-4e67-811f-55426a17b1b1.png">
<img width="188" alt="Screen Shot 2022-04-12 at 4 27 19 PM" src="https://user-images.githubusercontent.com/90487207/163072796-897191b9-0519-4e06-92bc-f67ea7e099be.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to post and insert into the locations table so that it shows, this will happen after every sign in 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to import a google maps package that displays on the screen
- [x] Update button component to enable and update location
- [x] Use the navigation.geolocation object to indicate where the location is and send it to the server db
- [x] Make sure that the location has some sort of radius showing
- [x] can manually input a city name to drop a pin in the location

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
