### ISSUE TITLE
Feature 3: User can View Profiles

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can View their profile
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The User will be take to the home screen where they are able to see their profile
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="476" alt="Screen Shot 2022-04-20 at 3 53 16 PM" src="https://user-images.githubusercontent.com/90487207/164337893-f5d6c238-49d9-4cfa-98e2-b1a101806341.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Make a fetch GET for profile/userProfile

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...
- [x] make a NAV component
- [x] make sure the data is from request is correct
- [x] have the sizing be good for the image
- [x] make sure to include a possible jumbotron for the top
- [x] make sure that it works for mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
