### ISSUE TITLE
Feature 4: User can Match with other Users

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add other users to a match list 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="627" alt="Screen Shot 2022-04-21 at 9 45 52 AM" src="https://user-images.githubusercontent.com/90487207/164511135-2447ac70-1926-4259-a60d-61fd7b3aca97.png">
<img width="846" alt="Screen Shot 2022-04-21 at 9 45 37 AM" src="https://user-images.githubusercontent.com/90487207/164511140-f5e32bcd-35f3-4bfe-8978-262ceb4ea73f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [ ] 

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] send a request for userProfiles
- [x] add a button that will send a post request to the matches table
- [x] make sure the table correctly displays data
- [x] post request for green check mark matches table is true
- [x] post request for x is false

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...
- [x] create component/function that adds a check or x button on the profile screen
- [ ] 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
