### ISSUE TITLE
Feature: User can reject Other users

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can reject requests
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When going to the matches screen, the user can click the x button to reject the user
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="846" alt="Screen Shot 2022-04-21 at 9 45 37 AM" src="https://user-images.githubusercontent.com/90487207/164758572-1ef650ea-8fe5-4f62-9905-3d1940ce1fb0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] Update the db so that isMatched field is false instead of true

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Make a post request 

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...
- [x] create component for button 
- [x] Make the have bar  have a clean line
- [x] clean up components and try to have a geolocation blocker

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
