### ISSUE TITLE
Feature: User can View their Matches

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/Aquaint#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can View Their Matches

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the User clicks on their matches anchor, it will take them to a screen list of their matches

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="511" alt="Screen Shot 2022-04-24 at 12 58 34 AM" src="https://user-images.githubusercontent.com/90487207/164966382-664abc81-ac2e-4317-8d29-b0c010232ed4.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...
- [x] get request matches profile

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to view a page with all the matches
- [x] Update component to be able to click on individual profiles/maybe do that in another feature/issue

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
